# Generated by Django 5.2.2 on 2025-06-11 18:49

import common.model_fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmcAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('cmc_id', models.BigIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(max_length=16)),
                ('slug', models.CharField(blank=True, max_length=64, null=True)),
                ('platform', models.JSONField(blank=True, null=True)),
                ('num_market_pairs', models.IntegerField(blank=True, help_text='Number of market pairs', null=True)),
                ('date_added', models.DateTimeField(blank=True, help_text='Date when asset was added on CMC', null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags from CMC')),
                ('max_supply', common.model_fields.DecField(blank=True, decimal_places=0, help_text='Max supply of the asset', max_digits=65, null=True)),
                ('infinite_supply', models.BooleanField(default=False, help_text='Whether the supply is infinite')),
                ('self_reported_circulating_supply', common.model_fields.DecField(blank=True, decimal_places=8, help_text='Self-reported circulating supply', max_digits=65, null=True)),
                ('self_reported_market_cap', common.model_fields.DecField(blank=True, decimal_places=8, help_text='Self-reported market cap', max_digits=65, null=True)),
                ('tvl_ratio', models.FloatField(blank=True, help_text='TVL ratio', null=True)),
            ],
            options={
                'verbose_name': 'CMC 币种元信息',
                'verbose_name_plural': 'CMC 币种元信息',
                'db_table': 'cmc_assets',
            },
        ),
        migrations.CreateModel(
            name='CmcMarketData',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='market_data', serialize=False, to='cmc_proxy.cmcasset')),
                ('timestamp', models.DateTimeField(db_index=True, help_text='cmc_api 最后更新时间')),
                ('price_usd', common.model_fields.DecField(blank=True, decimal_places=18, max_digits=40, null=True)),
                ('market_cap', common.model_fields.DecField(blank=True, decimal_places=8, max_digits=40, null=True)),
                ('fully_diluted_market_cap', common.model_fields.DecField(blank=True, decimal_places=8, max_digits=40, null=True)),
                ('volume_24h', common.model_fields.DecField(blank=True, decimal_places=8, max_digits=40, null=True)),
                ('volume_change_24h', models.FloatField(blank=True, null=True)),
                ('percent_change_1h', models.FloatField(blank=True, null=True)),
                ('percent_change_24h', models.FloatField(blank=True, null=True)),
                ('percent_change_7d', models.FloatField(blank=True, null=True)),
                ('percent_change_30d', models.FloatField(blank=True, null=True)),
                ('percent_change_60d', models.FloatField(blank=True, null=True)),
                ('percent_change_90d', models.FloatField(blank=True, null=True)),
                ('market_cap_dominance', models.FloatField(blank=True, null=True)),
                ('tvl', common.model_fields.DecField(blank=True, decimal_places=8, max_digits=40, null=True)),
                ('volume_24h_token_count', common.model_fields.DecField(decimal_places=8, max_digits=40, null=True)),
                ('circulating_supply', common.model_fields.DecField(blank=True, decimal_places=8, max_digits=40, null=True)),
                ('total_supply', common.model_fields.DecField(blank=True, decimal_places=8, max_digits=40, null=True)),
                ('cmc_rank', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CMC 最新行情',
                'verbose_name_plural': 'CMC 最新行情',
                'db_table': 'cmc_market_data',
            },
        ),
        migrations.CreateModel(
            name='CmcKline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('timeframe', models.CharField(db_index=True, max_length=10)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open', common.model_fields.DecField(decimal_places=18, max_digits=40)),
                ('high', common.model_fields.DecField(decimal_places=18, max_digits=40)),
                ('low', common.model_fields.DecField(decimal_places=18, max_digits=40)),
                ('close', common.model_fields.DecField(decimal_places=18, max_digits=40)),
                ('volume', common.model_fields.DecField(decimal_places=8, max_digits=40)),
                ('volume_token_count', common.model_fields.DecField(decimal_places=8, max_digits=40, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klines', to='cmc_proxy.cmcasset')),
            ],
            options={
                'verbose_name': 'CMC K 线',
                'verbose_name_plural': 'CMC K 线',
                'db_table': 'cmc_klines',
                'unique_together': {('asset', 'timeframe', 'timestamp')},
            },
        ),
    ]
