# Generated by Django 5.2.2 on 2025-06-11 18:49

import common.model_fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmc_proxy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenHoldingsSummary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='holdings_summary', serialize=False, to='cmc_proxy.cmcasset')),
                ('fgp', models.FloatField(help_text='前几大持有者占比总和')),
                ('sgp', models.FloatField(blank=True, help_text='二级持有者占比', null=True)),
                ('show_sgp', models.BooleanField(default=False, help_text='是否显示二级占比')),
                ('others', models.FloatField(help_text='其他持有者占比')),
                ('holder_count', models.IntegerField(help_text='持有者总数')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='最后更新时间')),
            ],
            options={
                'verbose_name': '代币持仓汇总',
                'verbose_name_plural': '代币持仓汇总',
                'db_table': 'token_holdings_summary',
            },
        ),
        migrations.CreateModel(
            name='TokenHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('platform_id', models.IntegerField(help_text='区块链平台ID')),
                ('token_address', models.CharField(help_text='代币合约地址', max_length=255)),
                ('token_creator', models.BooleanField(default=False, help_text='是否为代币创建者')),
                ('address', models.CharField(db_index=True, help_text='持有者地址', max_length=255)),
                ('balance', common.model_fields.DecField(decimal_places=18, help_text='持有数量', max_digits=40)),
                ('percent', models.FloatField(help_text='占比百分比')),
                ('order', models.IntegerField(help_text='排名')),
                ('price', common.model_fields.DecField(blank=True, decimal_places=18, help_text='代币价格', max_digits=40, null=True)),
                ('total_amount', common.model_fields.DecField(blank=True, decimal_places=8, help_text='持仓总金额(USD)', max_digits=40, null=True)),
                ('explorer_url', models.URLField(blank=True, help_text='区块浏览器地址', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='最后更新时间')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='cmc_proxy.cmcasset')),
            ],
            options={
                'verbose_name': '代币持有者',
                'verbose_name_plural': '代币持有者',
                'db_table': 'token_holders',
                'ordering': ['order'],
                'unique_together': {('asset', 'address')},
            },
        ),
    ]
