# Generated by Django 2.2.3 on 2022-08-07 08:28

import django.db.models.deletion
from django.db import migrations, models

import common.model_fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtcAssetPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('usd_price', common.model_fields.DecField(decimal_places=30, default=0, max_digits=65)),
                ('cny_price', common.model_fields.DecField(decimal_places=30, default=0, max_digits=65)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                            related_name='otc_asset', to='exchange.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='MgObPersistence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('sell_price', common.model_fields.DecField(decimal_places=30, default=0, max_digits=65)),
                ('buy_price', common.model_fields.DecField(decimal_places=30, default=0, max_digits=65)),
                ('usd_price', common.model_fields.DecField(decimal_places=30, default=0, max_digits=65)),
                ('cny_price', common.model_fields.DecField(decimal_places=30, default=0, max_digits=65)),
                ('avg_price', common.model_fields.DecField(decimal_places=30, default=0, max_digits=65)),
                ('margin', common.model_fields.DecField(decimal_places=30, default=0, max_digits=65)),
                ('ratio', common.model_fields.DecField(decimal_places=30, default=0, max_digits=65)),
                ('base_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='base_asset', to='exchange.Asset')),
                ('quote_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                  related_name='quote_asset', to='exchange.Asset')),
                ('symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                             related_name='price_symbol', to='exchange.Symbol')),
            ],
        ),
    ]
