# Generated by Django 4.1 on 2022-09-24 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('exchange', '0002_asset_is_stable'),
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mgobpersistence',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='price_exchange', to='exchange.exchange'),
        ),
    ]
