# Generated by Django 2.2.3 on 2022-10-01 07:12

from django.db import migrations

import common.model_fields


class Migration(migrations.Migration):
    dependencies = [
        ('backoffice', '0002_mgobpersistence_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='otcassetprice',
            name='margin',
            field=common.model_fields.DecField(decimal_places=30, default=0, max_digits=65),
        ),
    ]
