# Generated by Django 5.1.6 on 2025-04-22 01:59

from django.db import migrations, models

import common.model_fields


class Migration(migrations.Migration):
    dependencies = [
        ('backoffice', '0003_otcassetprice_margin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('base_currency', models.CharField(db_index=True, help_text='e.g., USD', max_length=10)),
                ('quote_currency', models.CharField(db_index=True, help_text='e.g., CNY', max_length=10)),
                ('rate', common.model_fields.DecField(decimal_places=30, default=0,
                                                      help_text='The exchange rate (1 base_currency = rate * quote_currency)',
                                                      max_digits=65)),
                ('last_updated',
                 models.DateTimeField(auto_now=True, help_text='Timestamp when the rate was last updated')),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'unique_together': {('base_currency', 'quote_currency')},
            },
        ),
    ]
