# Generated by Django 5.2.2 on 2025-06-11 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmc_id', models.IntegerField(unique=True, verbose_name='CMC ID')),
                ('name', models.CharField(max_length=255, verbose_name='代币名称')),
                ('symbol', models.CharField(max_length=50, verbose_name='代币符号')),
                ('next_unlock_date', models.DateTimeField(blank=True, null=True, verbose_name='下次解锁日期')),
                ('next_unlock_amount', models.DecimalField(blank=True, decimal_places=10, max_digits=50, null=True, verbose_name='下次解锁数量')),
                ('next_unlock_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='下次解锁百分比')),
                ('total_locked', models.DecimalField(blank=True, decimal_places=10, max_digits=50, null=True, verbose_name='总锁仓量')),
                ('total_unlocked', models.DecimalField(blank=True, decimal_places=10, max_digits=50, null=True, verbose_name='已解锁量')),
                ('total_supply', models.DecimalField(blank=True, decimal_places=10, max_digits=50, null=True, verbose_name='总供应量')),
                ('locked_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='锁仓百分比')),
                ('unlocked_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='释放百分比')),
                ('max_supply', models.DecimalField(blank=True, decimal_places=10, max_digits=50, null=True, verbose_name='最大供应量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '代币解锁',
                'verbose_name_plural': '代币解锁',
                'db_table': 'token_unlocks',
            },
        ),
        migrations.CreateModel(
            name='UnlockEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlock_date', models.DateTimeField(verbose_name='解锁日期')),
                ('unlock_amount', models.DecimalField(decimal_places=10, max_digits=50, verbose_name='解锁数量')),
                ('unlock_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='解锁百分比')),
                ('allocation_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='分配名称')),
                ('vesting_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='归属类型')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='token_unlocks.tokenunlock', verbose_name='代币')),
            ],
            options={
                'verbose_name': '解锁事件',
                'verbose_name_plural': '解锁事件',
                'db_table': 'token_unlock_events',
                'ordering': ['unlock_date'],
            },
        ),
    ]
