# Generated by Django 4.1 on 2022-09-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_stable',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100,
                                   verbose_name='是否为稳定币'),
        ),
    ]
