# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dapplink import airdrop_pb2 as dapplink_dot_airdrop__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dapplink/airdrop_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AirdropServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.submitDppLinkPoints = channel.unary_unary(
                '/services.dapplink.airdrop.AirdropService/submitDppLinkPoints',
                request_serializer=dapplink_dot_airdrop__pb2.DppLinkPointsReq.SerializeToString,
                response_deserializer=dapplink_dot_airdrop__pb2.DppLinkPointsRep.FromString,
                _registered_method=True)


class AirdropServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def submitDppLinkPoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AirdropServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'submitDppLinkPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.submitDppLinkPoints,
                    request_deserializer=dapplink_dot_airdrop__pb2.DppLinkPointsReq.FromString,
                    response_serializer=dapplink_dot_airdrop__pb2.DppLinkPointsRep.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'services.dapplink.airdrop.AirdropService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('services.dapplink.airdrop.AirdropService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AirdropService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def submitDppLinkPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.dapplink.airdrop.AirdropService/submitDppLinkPoints',
            dapplink_dot_airdrop__pb2.DppLinkPointsReq.SerializeToString,
            dapplink_dot_airdrop__pb2.DppLinkPointsRep.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
