# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dapplink import appchain_pb2 as dapplink_dot_appchain__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dapplink/appchain_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AppChainServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.L1StakerRewardsAmount = channel.unary_unary(
                '/services.dapplink.appchain.AppChainService/L1StakerRewardsAmount',
                request_serializer=dapplink_dot_appchain__pb2.L1StakerRewardsAmountRequest.SerializeToString,
                response_deserializer=dapplink_dot_appchain__pb2.L1StakerRewardsAmountResponse.FromString,
                _registered_method=True)
        self.L2StakerRewardsAmount = channel.unary_unary(
                '/services.dapplink.appchain.AppChainService/L2StakerRewardsAmount',
                request_serializer=dapplink_dot_appchain__pb2.L2StakerRewardsAmountRequest.SerializeToString,
                response_deserializer=dapplink_dot_appchain__pb2.L2StakerRewardsAmountResponse.FromString,
                _registered_method=True)


class AppChainServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def L1StakerRewardsAmount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def L2StakerRewardsAmount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AppChainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'L1StakerRewardsAmount': grpc.unary_unary_rpc_method_handler(
                    servicer.L1StakerRewardsAmount,
                    request_deserializer=dapplink_dot_appchain__pb2.L1StakerRewardsAmountRequest.FromString,
                    response_serializer=dapplink_dot_appchain__pb2.L1StakerRewardsAmountResponse.SerializeToString,
            ),
            'L2StakerRewardsAmount': grpc.unary_unary_rpc_method_handler(
                    servicer.L2StakerRewardsAmount,
                    request_deserializer=dapplink_dot_appchain__pb2.L2StakerRewardsAmountRequest.FromString,
                    response_serializer=dapplink_dot_appchain__pb2.L2StakerRewardsAmountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'services.dapplink.appchain.AppChainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('services.dapplink.appchain.AppChainService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AppChainService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def L1StakerRewardsAmount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.dapplink.appchain.AppChainService/L1StakerRewardsAmount',
            dapplink_dot_appchain__pb2.L1StakerRewardsAmountRequest.SerializeToString,
            dapplink_dot_appchain__pb2.L1StakerRewardsAmountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def L2StakerRewardsAmount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/services.dapplink.appchain.AppChainService/L2StakerRewardsAmount',
            dapplink_dot_appchain__pb2.L2StakerRewardsAmountRequest.SerializeToString,
            dapplink_dot_appchain__pb2.L2StakerRewardsAmountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
