# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dapplink/appchain.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'dapplink/appchain.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x64\x61pplink/appchain.proto\x12\x1aservices.dapplink.appchain\"\\\n\x1cL1StakerRewardsAmountRequest\x12\x10\n\x08\x63hain_id\x18\x01 \x01(\t\x12\x16\n\x0estaker_address\x18\x02 \x01(\t\x12\x12\n\nstrategies\x18\x03 \x01(\t\"Q\n\x1dL1StakerRewardsAmountResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06income\x18\x03 \x01(\t\"Z\n\x1cL2StakerRewardsAmountRequest\x12\x10\n\x08\x63hain_id\x18\x01 \x01(\t\x12\x16\n\x0estaker_address\x18\x02 \x01(\t\x12\x10\n\x08strategy\x18\x03 \x01(\t\"Q\n\x1dL2StakerRewardsAmountResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06income\x18\x03 \x01(\t2\xaf\x02\n\x0f\x41ppChainService\x12\x8c\x01\n\x15L1StakerRewardsAmount\x12\x38.services.dapplink.appchain.L1StakerRewardsAmountRequest\x1a\x39.services.dapplink.appchain.L1StakerRewardsAmountResponse\x12\x8c\x01\n\x15L2StakerRewardsAmount\x12\x38.services.dapplink.appchain.L2StakerRewardsAmountRequest\x1a\x39.services.dapplink.appchain.L2StakerRewardsAmountResponseB)\n\x15xyz.dapplink.appchainZ\x10./proto/appchainb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dapplink.appchain_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\025xyz.dapplink.appchainZ\020./proto/appchain'
  _globals['_L1STAKERREWARDSAMOUNTREQUEST']._serialized_start=55
  _globals['_L1STAKERREWARDSAMOUNTREQUEST']._serialized_end=147
  _globals['_L1STAKERREWARDSAMOUNTRESPONSE']._serialized_start=149
  _globals['_L1STAKERREWARDSAMOUNTRESPONSE']._serialized_end=230
  _globals['_L2STAKERREWARDSAMOUNTREQUEST']._serialized_start=232
  _globals['_L2STAKERREWARDSAMOUNTREQUEST']._serialized_end=322
  _globals['_L2STAKERREWARDSAMOUNTRESPONSE']._serialized_start=324
  _globals['_L2STAKERREWARDSAMOUNTRESPONSE']._serialized_end=405
  _globals['_APPCHAINSERVICE']._serialized_start=408
  _globals['_APPCHAINSERVICE']._serialized_end=711
# @@protoc_insertion_point(module_scope)
