# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dapplink/l3staking.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'dapplink/l3staking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x64\x61pplink/l3staking.proto\x12\x1bservices.dapplink.l3staking\"\x92\x02\n\x0eStakingNodeReq\x12\x16\n\x0e\x63onsumer_token\x18\x01 \x01(\t\x12\x10\n\x08\x63hain_id\x18\x02 \x01(\t\x12\x10\n\x08strategy\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\t\x12\x12\n\neth_income\x18\x05 \x01(\t\x12\x17\n\x0f\x65th_income_rate\x18\x06 \x01(\t\x12\x11\n\tdp_income\x18\x07 \x01(\t\x12\x16\n\x0e\x64p_income_rate\x18\x08 \x01(\t\x12\x10\n\x08\x65th_evil\x18\t \x01(\t\x12\x15\n\reth_evil_rate\x18\n \x01(\t\x12\x0f\n\x07\x64p_evil\x18\x0b \x01(\t\x12\x14\n\x0c\x64p_evil_rate\x18\x0c \x01(\t\x12\x0b\n\x03tvl\x18\r \x01(\t\"+\n\x0eStakingNodeRep\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0b\n\x03msg\x18\x02 \x01(\t2\x89\x01\n\x10L3StakingService\x12u\n\x17updateStakingNodeIncome\x12+.services.dapplink.l3staking.StakingNodeReq\x1a+.services.dapplink.l3staking.StakingNodeRep\"\x00\x42+\n\x16xyz.dapplink.l3stakingZ\x11./proto/l3stakingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dapplink.l3staking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026xyz.dapplink.l3stakingZ\021./proto/l3staking'
  _globals['_STAKINGNODEREQ']._serialized_start=58
  _globals['_STAKINGNODEREQ']._serialized_end=332
  _globals['_STAKINGNODEREP']._serialized_start=334
  _globals['_STAKINGNODEREP']._serialized_end=377
  _globals['_L3STAKINGSERVICE']._serialized_start=380
  _globals['_L3STAKINGSERVICE']._serialized_end=517
# @@protoc_insertion_point(module_scope)
