# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dapplink import wallet_pb2 as dapplink_dot_wallet__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dapplink/wallet_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WalletServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getSupportCoins = channel.unary_unary(
                '/dapplink.wallet.WalletService/getSupportCoins',
                request_serializer=dapplink_dot_wallet__pb2.SupportCoinsRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.SupportCoinsResponse.FromString,
                _registered_method=True)
        self.convertAddress = channel.unary_unary(
                '/dapplink.wallet.WalletService/convertAddress',
                request_serializer=dapplink_dot_wallet__pb2.ConvertAddressRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.ConvertAddressResponse.FromString,
                _registered_method=True)
        self.validAddress = channel.unary_unary(
                '/dapplink.wallet.WalletService/validAddress',
                request_serializer=dapplink_dot_wallet__pb2.ValidAddressRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.ValidAddressResponse.FromString,
                _registered_method=True)
        self.getBlock = channel.unary_unary(
                '/dapplink.wallet.WalletService/getBlock',
                request_serializer=dapplink_dot_wallet__pb2.BlockRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.BlockResponse.FromString,
                _registered_method=True)
        self.getBlockHeaderByNumber = channel.unary_unary(
                '/dapplink.wallet.WalletService/getBlockHeaderByNumber',
                request_serializer=dapplink_dot_wallet__pb2.BlockHeaderRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.BlockHeaderResponse.FromString,
                _registered_method=True)
        self.getNonce = channel.unary_unary(
                '/dapplink.wallet.WalletService/getNonce',
                request_serializer=dapplink_dot_wallet__pb2.NonceRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.NonceResponse.FromString,
                _registered_method=True)
        self.getGasPrice = channel.unary_unary(
                '/dapplink.wallet.WalletService/getGasPrice',
                request_serializer=dapplink_dot_wallet__pb2.GasPriceRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.GasPriceResponse.FromString,
                _registered_method=True)
        self.getBalance = channel.unary_unary(
                '/dapplink.wallet.WalletService/getBalance',
                request_serializer=dapplink_dot_wallet__pb2.BalanceRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.BalanceResponse.FromString,
                _registered_method=True)
        self.getAccount = channel.unary_unary(
                '/dapplink.wallet.WalletService/getAccount',
                request_serializer=dapplink_dot_wallet__pb2.AccountRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.AccountResponse.FromString,
                _registered_method=True)
        self.getMinRent = channel.unary_unary(
                '/dapplink.wallet.WalletService/getMinRent',
                request_serializer=dapplink_dot_wallet__pb2.MinRentRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.MinRentResponse.FromString,
                _registered_method=True)
        self.SendTx = channel.unary_unary(
                '/dapplink.wallet.WalletService/SendTx',
                request_serializer=dapplink_dot_wallet__pb2.SendTxRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.SendTxResponse.FromString,
                _registered_method=True)
        self.getTxByAddress = channel.unary_unary(
                '/dapplink.wallet.WalletService/getTxByAddress',
                request_serializer=dapplink_dot_wallet__pb2.TxAddressRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.TxAddressResponse.FromString,
                _registered_method=True)
        self.getTxByHash = channel.unary_unary(
                '/dapplink.wallet.WalletService/getTxByHash',
                request_serializer=dapplink_dot_wallet__pb2.TxHashRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.TxHashResponse.FromString,
                _registered_method=True)
        self.getUtxo = channel.unary_unary(
                '/dapplink.wallet.WalletService/getUtxo',
                request_serializer=dapplink_dot_wallet__pb2.UtxoRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.UtxoResponse.FromString,
                _registered_method=True)
        self.getUnspentOutputs = channel.unary_unary(
                '/dapplink.wallet.WalletService/getUnspentOutputs',
                request_serializer=dapplink_dot_wallet__pb2.UnspentOutputsRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.UnspentOutputsResponse.FromString,
                _registered_method=True)
        self.getUtxoInsFromData = channel.unary_unary(
                '/dapplink.wallet.WalletService/getUtxoInsFromData',
                request_serializer=dapplink_dot_wallet__pb2.UtxoInsFromDataRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.UtxoInsResponse.FromString,
                _registered_method=True)
        self.getAccountTxFromData = channel.unary_unary(
                '/dapplink.wallet.WalletService/getAccountTxFromData',
                request_serializer=dapplink_dot_wallet__pb2.TxFromDataRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.AccountTxResponse.FromString,
                _registered_method=True)
        self.getUtxoTxFromData = channel.unary_unary(
                '/dapplink.wallet.WalletService/getUtxoTxFromData',
                request_serializer=dapplink_dot_wallet__pb2.TxFromDataRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.UtxoTxResponse.FromString,
                _registered_method=True)
        self.getAccountTxFromSignedData = channel.unary_unary(
                '/dapplink.wallet.WalletService/getAccountTxFromSignedData',
                request_serializer=dapplink_dot_wallet__pb2.TxFromSignedDataRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.AccountTxResponse.FromString,
                _registered_method=True)
        self.GetUtxoTxFromSignedData = channel.unary_unary(
                '/dapplink.wallet.WalletService/GetUtxoTxFromSignedData',
                request_serializer=dapplink_dot_wallet__pb2.TxFromSignedDataRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.UtxoTxResponse.FromString,
                _registered_method=True)
        self.createAccountSignedTx = channel.unary_unary(
                '/dapplink.wallet.WalletService/createAccountSignedTx',
                request_serializer=dapplink_dot_wallet__pb2.CreateAccountSignedTxRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.CreateSignedTxResponse.FromString,
                _registered_method=True)
        self.createAccountTx = channel.unary_unary(
                '/dapplink.wallet.WalletService/createAccountTx',
                request_serializer=dapplink_dot_wallet__pb2.CreateAccountTxRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.CreateAccountTxResponse.FromString,
                _registered_method=True)
        self.createUtxoSignedTx = channel.unary_unary(
                '/dapplink.wallet.WalletService/createUtxoSignedTx',
                request_serializer=dapplink_dot_wallet__pb2.CreateUtxoSignedTxRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.CreateSignedTxResponse.FromString,
                _registered_method=True)
        self.createUtxoTx = channel.unary_unary(
                '/dapplink.wallet.WalletService/createUtxoTx',
                request_serializer=dapplink_dot_wallet__pb2.CreateUtxoTxRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.CreateUtxoTxResponse.FromString,
                _registered_method=True)
        self.verifyAccountSignedTx = channel.unary_unary(
                '/dapplink.wallet.WalletService/verifyAccountSignedTx',
                request_serializer=dapplink_dot_wallet__pb2.VerifySignedTxRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.VerifySignedTxResponse.FromString,
                _registered_method=True)
        self.verifyUtxoSignedTx = channel.unary_unary(
                '/dapplink.wallet.WalletService/verifyUtxoSignedTx',
                request_serializer=dapplink_dot_wallet__pb2.VerifySignedTxRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.VerifySignedTxResponse.FromString,
                _registered_method=True)
        self.ABIBinToJSON = channel.unary_unary(
                '/dapplink.wallet.WalletService/ABIBinToJSON',
                request_serializer=dapplink_dot_wallet__pb2.ABIBinToJSONRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.ABIBinToJSONResponse.FromString,
                _registered_method=True)
        self.ABIJSONToBin = channel.unary_unary(
                '/dapplink.wallet.WalletService/ABIJSONToBin',
                request_serializer=dapplink_dot_wallet__pb2.ABIJSONToBinRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.ABIJSONToBinResponse.FromString,
                _registered_method=True)
        self.getBlockByNumber = channel.unary_unary(
                '/dapplink.wallet.WalletService/getBlockByNumber',
                request_serializer=dapplink_dot_wallet__pb2.BlockInfoRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.BlockInfoResponse.FromString,
                _registered_method=True)
        self.getLatestSafeBlockHeader = channel.unary_unary(
                '/dapplink.wallet.WalletService/getLatestSafeBlockHeader',
                request_serializer=dapplink_dot_wallet__pb2.BasicRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.BlockHeaderResponse.FromString,
                _registered_method=True)
        self.getLatestFinalizedBlockHeader = channel.unary_unary(
                '/dapplink.wallet.WalletService/getLatestFinalizedBlockHeader',
                request_serializer=dapplink_dot_wallet__pb2.BasicRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.BlockHeaderResponse.FromString,
                _registered_method=True)
        self.getBlockHeaderByHash = channel.unary_unary(
                '/dapplink.wallet.WalletService/getBlockHeaderByHash',
                request_serializer=dapplink_dot_wallet__pb2.BlockHeaderByHashRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.BlockHeaderResponse.FromString,
                _registered_method=True)
        self.GetBlockByRange = channel.unary_unary(
                '/dapplink.wallet.WalletService/GetBlockByRange',
                request_serializer=dapplink_dot_wallet__pb2.BlockByRangeRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.BlockByRangeResponse.FromString,
                _registered_method=True)
        self.getTxReceiptByHash = channel.unary_unary(
                '/dapplink.wallet.WalletService/getTxReceiptByHash',
                request_serializer=dapplink_dot_wallet__pb2.TxReceiptByHashRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.TxReceiptByHashResponse.FromString,
                _registered_method=True)
        self.getStorageHash = channel.unary_unary(
                '/dapplink.wallet.WalletService/getStorageHash',
                request_serializer=dapplink_dot_wallet__pb2.StorageHashRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.StorageHashResponse.FromString,
                _registered_method=True)
        self.getFilterLogs = channel.unary_unary(
                '/dapplink.wallet.WalletService/getFilterLogs',
                request_serializer=dapplink_dot_wallet__pb2.FilterLogsRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.FilterLogsResponse.FromString,
                _registered_method=True)
        self.getTxCountByAddress = channel.unary_unary(
                '/dapplink.wallet.WalletService/getTxCountByAddress',
                request_serializer=dapplink_dot_wallet__pb2.TxCountByAddressRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.TxCountByAddressResponse.FromString,
                _registered_method=True)
        self.getSuggestGasPrice = channel.unary_unary(
                '/dapplink.wallet.WalletService/getSuggestGasPrice',
                request_serializer=dapplink_dot_wallet__pb2.SuggestGasPriceRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.SuggestGasPriceResponse.FromString,
                _registered_method=True)
        self.getSuggestGasTipCap = channel.unary_unary(
                '/dapplink.wallet.WalletService/getSuggestGasTipCap',
                request_serializer=dapplink_dot_wallet__pb2.SuggestGasPriceRequest.SerializeToString,
                response_deserializer=dapplink_dot_wallet__pb2.SuggestGasPriceResponse.FromString,
                _registered_method=True)


class WalletServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getSupportCoins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def convertAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def validAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getBlockHeaderByNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getNonce(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getGasPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getMinRent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTx(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getTxByAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getTxByHash(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getUtxo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getUnspentOutputs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getUtxoInsFromData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getAccountTxFromData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getUtxoTxFromData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getAccountTxFromSignedData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUtxoTxFromSignedData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createAccountSignedTx(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createAccountTx(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createUtxoSignedTx(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createUtxoTx(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def verifyAccountSignedTx(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def verifyUtxoSignedTx(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ABIBinToJSON(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ABIJSONToBin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getBlockByNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getLatestSafeBlockHeader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getLatestFinalizedBlockHeader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getBlockHeaderByHash(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBlockByRange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getTxReceiptByHash(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getStorageHash(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getFilterLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getTxCountByAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getSuggestGasPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getSuggestGasTipCap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WalletServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getSupportCoins': grpc.unary_unary_rpc_method_handler(
                    servicer.getSupportCoins,
                    request_deserializer=dapplink_dot_wallet__pb2.SupportCoinsRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.SupportCoinsResponse.SerializeToString,
            ),
            'convertAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.convertAddress,
                    request_deserializer=dapplink_dot_wallet__pb2.ConvertAddressRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.ConvertAddressResponse.SerializeToString,
            ),
            'validAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.validAddress,
                    request_deserializer=dapplink_dot_wallet__pb2.ValidAddressRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.ValidAddressResponse.SerializeToString,
            ),
            'getBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.getBlock,
                    request_deserializer=dapplink_dot_wallet__pb2.BlockRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.BlockResponse.SerializeToString,
            ),
            'getBlockHeaderByNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.getBlockHeaderByNumber,
                    request_deserializer=dapplink_dot_wallet__pb2.BlockHeaderRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.BlockHeaderResponse.SerializeToString,
            ),
            'getNonce': grpc.unary_unary_rpc_method_handler(
                    servicer.getNonce,
                    request_deserializer=dapplink_dot_wallet__pb2.NonceRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.NonceResponse.SerializeToString,
            ),
            'getGasPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.getGasPrice,
                    request_deserializer=dapplink_dot_wallet__pb2.GasPriceRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.GasPriceResponse.SerializeToString,
            ),
            'getBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.getBalance,
                    request_deserializer=dapplink_dot_wallet__pb2.BalanceRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.BalanceResponse.SerializeToString,
            ),
            'getAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.getAccount,
                    request_deserializer=dapplink_dot_wallet__pb2.AccountRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.AccountResponse.SerializeToString,
            ),
            'getMinRent': grpc.unary_unary_rpc_method_handler(
                    servicer.getMinRent,
                    request_deserializer=dapplink_dot_wallet__pb2.MinRentRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.MinRentResponse.SerializeToString,
            ),
            'SendTx': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTx,
                    request_deserializer=dapplink_dot_wallet__pb2.SendTxRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.SendTxResponse.SerializeToString,
            ),
            'getTxByAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.getTxByAddress,
                    request_deserializer=dapplink_dot_wallet__pb2.TxAddressRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.TxAddressResponse.SerializeToString,
            ),
            'getTxByHash': grpc.unary_unary_rpc_method_handler(
                    servicer.getTxByHash,
                    request_deserializer=dapplink_dot_wallet__pb2.TxHashRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.TxHashResponse.SerializeToString,
            ),
            'getUtxo': grpc.unary_unary_rpc_method_handler(
                    servicer.getUtxo,
                    request_deserializer=dapplink_dot_wallet__pb2.UtxoRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.UtxoResponse.SerializeToString,
            ),
            'getUnspentOutputs': grpc.unary_unary_rpc_method_handler(
                    servicer.getUnspentOutputs,
                    request_deserializer=dapplink_dot_wallet__pb2.UnspentOutputsRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.UnspentOutputsResponse.SerializeToString,
            ),
            'getUtxoInsFromData': grpc.unary_unary_rpc_method_handler(
                    servicer.getUtxoInsFromData,
                    request_deserializer=dapplink_dot_wallet__pb2.UtxoInsFromDataRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.UtxoInsResponse.SerializeToString,
            ),
            'getAccountTxFromData': grpc.unary_unary_rpc_method_handler(
                    servicer.getAccountTxFromData,
                    request_deserializer=dapplink_dot_wallet__pb2.TxFromDataRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.AccountTxResponse.SerializeToString,
            ),
            'getUtxoTxFromData': grpc.unary_unary_rpc_method_handler(
                    servicer.getUtxoTxFromData,
                    request_deserializer=dapplink_dot_wallet__pb2.TxFromDataRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.UtxoTxResponse.SerializeToString,
            ),
            'getAccountTxFromSignedData': grpc.unary_unary_rpc_method_handler(
                    servicer.getAccountTxFromSignedData,
                    request_deserializer=dapplink_dot_wallet__pb2.TxFromSignedDataRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.AccountTxResponse.SerializeToString,
            ),
            'GetUtxoTxFromSignedData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUtxoTxFromSignedData,
                    request_deserializer=dapplink_dot_wallet__pb2.TxFromSignedDataRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.UtxoTxResponse.SerializeToString,
            ),
            'createAccountSignedTx': grpc.unary_unary_rpc_method_handler(
                    servicer.createAccountSignedTx,
                    request_deserializer=dapplink_dot_wallet__pb2.CreateAccountSignedTxRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.CreateSignedTxResponse.SerializeToString,
            ),
            'createAccountTx': grpc.unary_unary_rpc_method_handler(
                    servicer.createAccountTx,
                    request_deserializer=dapplink_dot_wallet__pb2.CreateAccountTxRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.CreateAccountTxResponse.SerializeToString,
            ),
            'createUtxoSignedTx': grpc.unary_unary_rpc_method_handler(
                    servicer.createUtxoSignedTx,
                    request_deserializer=dapplink_dot_wallet__pb2.CreateUtxoSignedTxRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.CreateSignedTxResponse.SerializeToString,
            ),
            'createUtxoTx': grpc.unary_unary_rpc_method_handler(
                    servicer.createUtxoTx,
                    request_deserializer=dapplink_dot_wallet__pb2.CreateUtxoTxRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.CreateUtxoTxResponse.SerializeToString,
            ),
            'verifyAccountSignedTx': grpc.unary_unary_rpc_method_handler(
                    servicer.verifyAccountSignedTx,
                    request_deserializer=dapplink_dot_wallet__pb2.VerifySignedTxRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.VerifySignedTxResponse.SerializeToString,
            ),
            'verifyUtxoSignedTx': grpc.unary_unary_rpc_method_handler(
                    servicer.verifyUtxoSignedTx,
                    request_deserializer=dapplink_dot_wallet__pb2.VerifySignedTxRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.VerifySignedTxResponse.SerializeToString,
            ),
            'ABIBinToJSON': grpc.unary_unary_rpc_method_handler(
                    servicer.ABIBinToJSON,
                    request_deserializer=dapplink_dot_wallet__pb2.ABIBinToJSONRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.ABIBinToJSONResponse.SerializeToString,
            ),
            'ABIJSONToBin': grpc.unary_unary_rpc_method_handler(
                    servicer.ABIJSONToBin,
                    request_deserializer=dapplink_dot_wallet__pb2.ABIJSONToBinRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.ABIJSONToBinResponse.SerializeToString,
            ),
            'getBlockByNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.getBlockByNumber,
                    request_deserializer=dapplink_dot_wallet__pb2.BlockInfoRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.BlockInfoResponse.SerializeToString,
            ),
            'getLatestSafeBlockHeader': grpc.unary_unary_rpc_method_handler(
                    servicer.getLatestSafeBlockHeader,
                    request_deserializer=dapplink_dot_wallet__pb2.BasicRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.BlockHeaderResponse.SerializeToString,
            ),
            'getLatestFinalizedBlockHeader': grpc.unary_unary_rpc_method_handler(
                    servicer.getLatestFinalizedBlockHeader,
                    request_deserializer=dapplink_dot_wallet__pb2.BasicRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.BlockHeaderResponse.SerializeToString,
            ),
            'getBlockHeaderByHash': grpc.unary_unary_rpc_method_handler(
                    servicer.getBlockHeaderByHash,
                    request_deserializer=dapplink_dot_wallet__pb2.BlockHeaderByHashRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.BlockHeaderResponse.SerializeToString,
            ),
            'GetBlockByRange': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBlockByRange,
                    request_deserializer=dapplink_dot_wallet__pb2.BlockByRangeRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.BlockByRangeResponse.SerializeToString,
            ),
            'getTxReceiptByHash': grpc.unary_unary_rpc_method_handler(
                    servicer.getTxReceiptByHash,
                    request_deserializer=dapplink_dot_wallet__pb2.TxReceiptByHashRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.TxReceiptByHashResponse.SerializeToString,
            ),
            'getStorageHash': grpc.unary_unary_rpc_method_handler(
                    servicer.getStorageHash,
                    request_deserializer=dapplink_dot_wallet__pb2.StorageHashRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.StorageHashResponse.SerializeToString,
            ),
            'getFilterLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.getFilterLogs,
                    request_deserializer=dapplink_dot_wallet__pb2.FilterLogsRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.FilterLogsResponse.SerializeToString,
            ),
            'getTxCountByAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.getTxCountByAddress,
                    request_deserializer=dapplink_dot_wallet__pb2.TxCountByAddressRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.TxCountByAddressResponse.SerializeToString,
            ),
            'getSuggestGasPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.getSuggestGasPrice,
                    request_deserializer=dapplink_dot_wallet__pb2.SuggestGasPriceRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.SuggestGasPriceResponse.SerializeToString,
            ),
            'getSuggestGasTipCap': grpc.unary_unary_rpc_method_handler(
                    servicer.getSuggestGasTipCap,
                    request_deserializer=dapplink_dot_wallet__pb2.SuggestGasPriceRequest.FromString,
                    response_serializer=dapplink_dot_wallet__pb2.SuggestGasPriceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dapplink.wallet.WalletService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dapplink.wallet.WalletService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WalletService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getSupportCoins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/getSupportCoins',
            dapplink_dot_wallet__pb2.SupportCoinsRequest.SerializeToString,
            dapplink_dot_wallet__pb2.SupportCoinsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def convertAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/convertAddress',
            dapplink_dot_wallet__pb2.ConvertAddressRequest.SerializeToString,
            dapplink_dot_wallet__pb2.ConvertAddressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def validAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/validAddress',
            dapplink_dot_wallet__pb2.ValidAddressRequest.SerializeToString,
            dapplink_dot_wallet__pb2.ValidAddressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/getBlock',
            dapplink_dot_wallet__pb2.BlockRequest.SerializeToString,
            dapplink_dot_wallet__pb2.BlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getBlockHeaderByNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/getBlockHeaderByNumber',
            dapplink_dot_wallet__pb2.BlockHeaderRequest.SerializeToString,
            dapplink_dot_wallet__pb2.BlockHeaderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getNonce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/getNonce',
            dapplink_dot_wallet__pb2.NonceRequest.SerializeToString,
            dapplink_dot_wallet__pb2.NonceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getGasPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/getGasPrice',
            dapplink_dot_wallet__pb2.GasPriceRequest.SerializeToString,
            dapplink_dot_wallet__pb2.GasPriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/getBalance',
            dapplink_dot_wallet__pb2.BalanceRequest.SerializeToString,
            dapplink_dot_wallet__pb2.BalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/getAccount',
            dapplink_dot_wallet__pb2.AccountRequest.SerializeToString,
            dapplink_dot_wallet__pb2.AccountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getMinRent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/getMinRent',
            dapplink_dot_wallet__pb2.MinRentRequest.SerializeToString,
            dapplink_dot_wallet__pb2.MinRentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendTx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/SendTx',
            dapplink_dot_wallet__pb2.SendTxRequest.SerializeToString,
            dapplink_dot_wallet__pb2.SendTxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getTxByAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/getTxByAddress',
            dapplink_dot_wallet__pb2.TxAddressRequest.SerializeToString,
            dapplink_dot_wallet__pb2.TxAddressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getTxByHash(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/getTxByHash',
            dapplink_dot_wallet__pb2.TxHashRequest.SerializeToString,
            dapplink_dot_wallet__pb2.TxHashResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getUtxo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/getUtxo',
            dapplink_dot_wallet__pb2.UtxoRequest.SerializeToString,
            dapplink_dot_wallet__pb2.UtxoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getUnspentOutputs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/getUnspentOutputs',
            dapplink_dot_wallet__pb2.UnspentOutputsRequest.SerializeToString,
            dapplink_dot_wallet__pb2.UnspentOutputsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getUtxoInsFromData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/getUtxoInsFromData',
            dapplink_dot_wallet__pb2.UtxoInsFromDataRequest.SerializeToString,
            dapplink_dot_wallet__pb2.UtxoInsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getAccountTxFromData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/getAccountTxFromData',
            dapplink_dot_wallet__pb2.TxFromDataRequest.SerializeToString,
            dapplink_dot_wallet__pb2.AccountTxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getUtxoTxFromData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/getUtxoTxFromData',
            dapplink_dot_wallet__pb2.TxFromDataRequest.SerializeToString,
            dapplink_dot_wallet__pb2.UtxoTxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getAccountTxFromSignedData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/getAccountTxFromSignedData',
            dapplink_dot_wallet__pb2.TxFromSignedDataRequest.SerializeToString,
            dapplink_dot_wallet__pb2.AccountTxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUtxoTxFromSignedData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/GetUtxoTxFromSignedData',
            dapplink_dot_wallet__pb2.TxFromSignedDataRequest.SerializeToString,
            dapplink_dot_wallet__pb2.UtxoTxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def createAccountSignedTx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/createAccountSignedTx',
            dapplink_dot_wallet__pb2.CreateAccountSignedTxRequest.SerializeToString,
            dapplink_dot_wallet__pb2.CreateSignedTxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def createAccountTx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/createAccountTx',
            dapplink_dot_wallet__pb2.CreateAccountTxRequest.SerializeToString,
            dapplink_dot_wallet__pb2.CreateAccountTxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def createUtxoSignedTx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/createUtxoSignedTx',
            dapplink_dot_wallet__pb2.CreateUtxoSignedTxRequest.SerializeToString,
            dapplink_dot_wallet__pb2.CreateSignedTxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def createUtxoTx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/createUtxoTx',
            dapplink_dot_wallet__pb2.CreateUtxoTxRequest.SerializeToString,
            dapplink_dot_wallet__pb2.CreateUtxoTxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def verifyAccountSignedTx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/verifyAccountSignedTx',
            dapplink_dot_wallet__pb2.VerifySignedTxRequest.SerializeToString,
            dapplink_dot_wallet__pb2.VerifySignedTxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def verifyUtxoSignedTx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/verifyUtxoSignedTx',
            dapplink_dot_wallet__pb2.VerifySignedTxRequest.SerializeToString,
            dapplink_dot_wallet__pb2.VerifySignedTxResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ABIBinToJSON(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/ABIBinToJSON',
            dapplink_dot_wallet__pb2.ABIBinToJSONRequest.SerializeToString,
            dapplink_dot_wallet__pb2.ABIBinToJSONResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ABIJSONToBin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/ABIJSONToBin',
            dapplink_dot_wallet__pb2.ABIJSONToBinRequest.SerializeToString,
            dapplink_dot_wallet__pb2.ABIJSONToBinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getBlockByNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/getBlockByNumber',
            dapplink_dot_wallet__pb2.BlockInfoRequest.SerializeToString,
            dapplink_dot_wallet__pb2.BlockInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getLatestSafeBlockHeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/getLatestSafeBlockHeader',
            dapplink_dot_wallet__pb2.BasicRequest.SerializeToString,
            dapplink_dot_wallet__pb2.BlockHeaderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getLatestFinalizedBlockHeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/getLatestFinalizedBlockHeader',
            dapplink_dot_wallet__pb2.BasicRequest.SerializeToString,
            dapplink_dot_wallet__pb2.BlockHeaderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getBlockHeaderByHash(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/getBlockHeaderByHash',
            dapplink_dot_wallet__pb2.BlockHeaderByHashRequest.SerializeToString,
            dapplink_dot_wallet__pb2.BlockHeaderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBlockByRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/GetBlockByRange',
            dapplink_dot_wallet__pb2.BlockByRangeRequest.SerializeToString,
            dapplink_dot_wallet__pb2.BlockByRangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getTxReceiptByHash(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/getTxReceiptByHash',
            dapplink_dot_wallet__pb2.TxReceiptByHashRequest.SerializeToString,
            dapplink_dot_wallet__pb2.TxReceiptByHashResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getStorageHash(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/getStorageHash',
            dapplink_dot_wallet__pb2.StorageHashRequest.SerializeToString,
            dapplink_dot_wallet__pb2.StorageHashResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getFilterLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/getFilterLogs',
            dapplink_dot_wallet__pb2.FilterLogsRequest.SerializeToString,
            dapplink_dot_wallet__pb2.FilterLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getTxCountByAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/getTxCountByAddress',
            dapplink_dot_wallet__pb2.TxCountByAddressRequest.SerializeToString,
            dapplink_dot_wallet__pb2.TxCountByAddressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getSuggestGasPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/getSuggestGasPrice',
            dapplink_dot_wallet__pb2.SuggestGasPriceRequest.SerializeToString,
            dapplink_dot_wallet__pb2.SuggestGasPriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getSuggestGasTipCap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.wallet.WalletService/getSuggestGasTipCap',
            dapplink_dot_wallet__pb2.SuggestGasPriceRequest.SerializeToString,
            dapplink_dot_wallet__pb2.SuggestGasPriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
