# Generated by Django 5.2.2 on 2025-06-11 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmc_id', models.IntegerField(unique=True, verbose_name='CMC ID')),
                ('name', models.CharField(max_length=255, verbose_name='代币名称')),
                ('symbol', models.CharField(max_length=50, verbose_name='代币符号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '代币分配',
                'verbose_name_plural': '代币分配',
                'db_table': 'token_allocations',
            },
        ),
        migrations.CreateModel(
            name='AllocationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='分配类别')),
                ('percentage', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='分配比例')),
                ('unlocked_percent', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='已解锁比例')),
                ('unlock_progress', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='解锁进度')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='token_economics.tokenallocation', verbose_name='代币')),
            ],
            options={
                'verbose_name': '分配类别',
                'verbose_name_plural': '分配类别',
                'db_table': 'token_allocation_categories',
            },
        ),
    ]
