# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from sevices.savourrpc import market_pb2 as dapplink_dot_market__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dapplink/market_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PriceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getExchanges = channel.unary_unary(
                '/dapplink.market.PriceService/getExchanges',
                request_serializer=dapplink_dot_market__pb2.ExchangeRequest.SerializeToString,
                response_deserializer=dapplink_dot_market__pb2.ExchangeResponse.FromString,
                _registered_method=True)
        self.getAssets = channel.unary_unary(
                '/dapplink.market.PriceService/getAssets',
                request_serializer=dapplink_dot_market__pb2.AssetRequest.SerializeToString,
                response_deserializer=dapplink_dot_market__pb2.AssetResponse.FromString,
                _registered_method=True)
        self.getSymbols = channel.unary_unary(
                '/dapplink.market.PriceService/getSymbols',
                request_serializer=dapplink_dot_market__pb2.SymbolRequest.SerializeToString,
                response_deserializer=dapplink_dot_market__pb2.SymbolResponse.FromString,
                _registered_method=True)
        self.getSymbolPrices = channel.unary_unary(
                '/dapplink.market.PriceService/getSymbolPrices',
                request_serializer=dapplink_dot_market__pb2.SymbolPriceRequest.SerializeToString,
                response_deserializer=dapplink_dot_market__pb2.SymbolPriceResponse.FromString,
                _registered_method=True)
        self.getStableCoins = channel.unary_unary(
                '/dapplink.market.PriceService/getStableCoins',
                request_serializer=dapplink_dot_market__pb2.StableCoinRequest.SerializeToString,
                response_deserializer=dapplink_dot_market__pb2.StableCoinResponse.FromString,
                _registered_method=True)
        self.getStableCoinPrice = channel.unary_unary(
                '/dapplink.market.PriceService/getStableCoinPrice',
                request_serializer=dapplink_dot_market__pb2.StableCoinPriceRequest.SerializeToString,
                response_deserializer=dapplink_dot_market__pb2.StableCoinPriceResponse.FromString,
                _registered_method=True)


class PriceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getExchanges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getAssets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getSymbols(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getSymbolPrices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getStableCoins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getStableCoinPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PriceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getExchanges': grpc.unary_unary_rpc_method_handler(
                    servicer.getExchanges,
                    request_deserializer=dapplink_dot_market__pb2.ExchangeRequest.FromString,
                    response_serializer=dapplink_dot_market__pb2.ExchangeResponse.SerializeToString,
            ),
            'getAssets': grpc.unary_unary_rpc_method_handler(
                    servicer.getAssets,
                    request_deserializer=dapplink_dot_market__pb2.AssetRequest.FromString,
                    response_serializer=dapplink_dot_market__pb2.AssetResponse.SerializeToString,
            ),
            'getSymbols': grpc.unary_unary_rpc_method_handler(
                    servicer.getSymbols,
                    request_deserializer=dapplink_dot_market__pb2.SymbolRequest.FromString,
                    response_serializer=dapplink_dot_market__pb2.SymbolResponse.SerializeToString,
            ),
            'getSymbolPrices': grpc.unary_unary_rpc_method_handler(
                    servicer.getSymbolPrices,
                    request_deserializer=dapplink_dot_market__pb2.SymbolPriceRequest.FromString,
                    response_serializer=dapplink_dot_market__pb2.SymbolPriceResponse.SerializeToString,
            ),
            'getStableCoins': grpc.unary_unary_rpc_method_handler(
                    servicer.getStableCoins,
                    request_deserializer=dapplink_dot_market__pb2.StableCoinRequest.FromString,
                    response_serializer=dapplink_dot_market__pb2.StableCoinResponse.SerializeToString,
            ),
            'getStableCoinPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.getStableCoinPrice,
                    request_deserializer=dapplink_dot_market__pb2.StableCoinPriceRequest.FromString,
                    response_serializer=dapplink_dot_market__pb2.StableCoinPriceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dapplink.market.PriceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dapplink.market.PriceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PriceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getExchanges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.market.PriceService/getExchanges',
            dapplink_dot_market__pb2.ExchangeRequest.SerializeToString,
            dapplink_dot_market__pb2.ExchangeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getAssets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.market.PriceService/getAssets',
            dapplink_dot_market__pb2.AssetRequest.SerializeToString,
            dapplink_dot_market__pb2.AssetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getSymbols(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.market.PriceService/getSymbols',
            dapplink_dot_market__pb2.SymbolRequest.SerializeToString,
            dapplink_dot_market__pb2.SymbolResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getSymbolPrices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.market.PriceService/getSymbolPrices',
            dapplink_dot_market__pb2.SymbolPriceRequest.SerializeToString,
            dapplink_dot_market__pb2.SymbolPriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getStableCoins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.market.PriceService/getStableCoins',
            dapplink_dot_market__pb2.StableCoinRequest.SerializeToString,
            dapplink_dot_market__pb2.StableCoinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getStableCoinPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dapplink.market.PriceService/getStableCoinPrice',
            dapplink_dot_market__pb2.StableCoinPriceRequest.SerializeToString,
            dapplink_dot_market__pb2.StableCoinPriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
