# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from sevices.savourrpc import wallet_pb2 as savourrpc_dot_wallet__pb2


class WalletServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getSupportCoins = channel.unary_unary(
            '/savourrpc.wallet.WalletService/getSupportCoins',
            request_serializer=savourrpc_dot_wallet__pb2.SupportCoinsRequest.SerializeToString,
            response_deserializer=savourrpc_dot_wallet__pb2.SupportCoinsResponse.FromString,
        )
        self.convertAddress = channel.unary_unary(
            '/savourrpc.wallet.WalletService/convertAddress',
            request_serializer=savourrpc_dot_wallet__pb2.ConvertAddressRequest.SerializeToString,
            response_deserializer=savourrpc_dot_wallet__pb2.ConvertAddressResponse.FromString,
        )
        self.validAddress = channel.unary_unary(
            '/savourrpc.wallet.WalletService/validAddress',
            request_serializer=savourrpc_dot_wallet__pb2.ValidAddressRequest.SerializeToString,
            response_deserializer=savourrpc_dot_wallet__pb2.ValidAddressResponse.FromString,
        )
        self.getNonce = channel.unary_unary(
            '/savourrpc.wallet.WalletService/getNonce',
            request_serializer=savourrpc_dot_wallet__pb2.NonceRequest.SerializeToString,
            response_deserializer=savourrpc_dot_wallet__pb2.NonceResponse.FromString,
        )
        self.getGasPrice = channel.unary_unary(
            '/savourrpc.wallet.WalletService/getGasPrice',
            request_serializer=savourrpc_dot_wallet__pb2.GasPriceRequest.SerializeToString,
            response_deserializer=savourrpc_dot_wallet__pb2.GasPriceResponse.FromString,
        )
        self.getBalance = channel.unary_unary(
            '/savourrpc.wallet.WalletService/getBalance',
            request_serializer=savourrpc_dot_wallet__pb2.BalanceRequest.SerializeToString,
            response_deserializer=savourrpc_dot_wallet__pb2.BalanceResponse.FromString,
        )
        self.getAccount = channel.unary_unary(
            '/savourrpc.wallet.WalletService/getAccount',
            request_serializer=savourrpc_dot_wallet__pb2.AccountRequest.SerializeToString,
            response_deserializer=savourrpc_dot_wallet__pb2.AccountResponse.FromString,
        )
        self.getMinRent = channel.unary_unary(
            '/savourrpc.wallet.WalletService/getMinRent',
            request_serializer=savourrpc_dot_wallet__pb2.MinRentRequest.SerializeToString,
            response_deserializer=savourrpc_dot_wallet__pb2.MinRentResponse.FromString,
        )
        self.SendTx = channel.unary_unary(
            '/savourrpc.wallet.WalletService/SendTx',
            request_serializer=savourrpc_dot_wallet__pb2.SendTxRequest.SerializeToString,
            response_deserializer=savourrpc_dot_wallet__pb2.SendTxResponse.FromString,
        )
        self.getTxByAddress = channel.unary_unary(
            '/savourrpc.wallet.WalletService/getTxByAddress',
            request_serializer=savourrpc_dot_wallet__pb2.TxAddressRequest.SerializeToString,
            response_deserializer=savourrpc_dot_wallet__pb2.TxAddressResponse.FromString,
        )
        self.getTxByHash = channel.unary_unary(
            '/savourrpc.wallet.WalletService/getTxByHash',
            request_serializer=savourrpc_dot_wallet__pb2.TxHashRequest.SerializeToString,
            response_deserializer=savourrpc_dot_wallet__pb2.TxHashResponse.FromString,
        )
        self.getUtxo = channel.unary_unary(
            '/savourrpc.wallet.WalletService/getUtxo',
            request_serializer=savourrpc_dot_wallet__pb2.UtxoRequest.SerializeToString,
            response_deserializer=savourrpc_dot_wallet__pb2.UtxoResponse.FromString,
        )
        self.getUtxoInsFromData = channel.unary_unary(
            '/savourrpc.wallet.WalletService/getUtxoInsFromData',
            request_serializer=savourrpc_dot_wallet__pb2.UtxoInsFromDataRequest.SerializeToString,
            response_deserializer=savourrpc_dot_wallet__pb2.UtxoInsResponse.FromString,
        )
        self.getAccountTxFromData = channel.unary_unary(
            '/savourrpc.wallet.WalletService/getAccountTxFromData',
            request_serializer=savourrpc_dot_wallet__pb2.TxFromDataRequest.SerializeToString,
            response_deserializer=savourrpc_dot_wallet__pb2.AccountTxResponse.FromString,
        )
        self.getUtxoTxFromData = channel.unary_unary(
            '/savourrpc.wallet.WalletService/getUtxoTxFromData',
            request_serializer=savourrpc_dot_wallet__pb2.TxFromDataRequest.SerializeToString,
            response_deserializer=savourrpc_dot_wallet__pb2.UtxoTxResponse.FromString,
        )
        self.getAccountTxFromSignedData = channel.unary_unary(
            '/savourrpc.wallet.WalletService/getAccountTxFromSignedData',
            request_serializer=savourrpc_dot_wallet__pb2.TxFromSignedDataRequest.SerializeToString,
            response_deserializer=savourrpc_dot_wallet__pb2.AccountTxResponse.FromString,
        )
        self.GetUtxoTxFromSignedData = channel.unary_unary(
            '/savourrpc.wallet.WalletService/GetUtxoTxFromSignedData',
            request_serializer=savourrpc_dot_wallet__pb2.TxFromSignedDataRequest.SerializeToString,
            response_deserializer=savourrpc_dot_wallet__pb2.UtxoTxResponse.FromString,
        )
        self.createAccountSignedTx = channel.unary_unary(
            '/savourrpc.wallet.WalletService/createAccountSignedTx',
            request_serializer=savourrpc_dot_wallet__pb2.CreateAccountSignedTxRequest.SerializeToString,
            response_deserializer=savourrpc_dot_wallet__pb2.CreateSignedTxResponse.FromString,
        )
        self.createAccountTx = channel.unary_unary(
            '/savourrpc.wallet.WalletService/createAccountTx',
            request_serializer=savourrpc_dot_wallet__pb2.CreateAccountTxRequest.SerializeToString,
            response_deserializer=savourrpc_dot_wallet__pb2.CreateAccountTxResponse.FromString,
        )
        self.createUtxoSignedTx = channel.unary_unary(
            '/savourrpc.wallet.WalletService/createUtxoSignedTx',
            request_serializer=savourrpc_dot_wallet__pb2.CreateUtxoSignedTxRequest.SerializeToString,
            response_deserializer=savourrpc_dot_wallet__pb2.CreateSignedTxResponse.FromString,
        )
        self.createUtxoTx = channel.unary_unary(
            '/savourrpc.wallet.WalletService/createUtxoTx',
            request_serializer=savourrpc_dot_wallet__pb2.CreateUtxoTxRequest.SerializeToString,
            response_deserializer=savourrpc_dot_wallet__pb2.CreateUtxoTxResponse.FromString,
        )
        self.verifyAccountSignedTx = channel.unary_unary(
            '/savourrpc.wallet.WalletService/verifyAccountSignedTx',
            request_serializer=savourrpc_dot_wallet__pb2.VerifySignedTxRequest.SerializeToString,
            response_deserializer=savourrpc_dot_wallet__pb2.VerifySignedTxResponse.FromString,
        )
        self.verifyUtxoSignedTx = channel.unary_unary(
            '/savourrpc.wallet.WalletService/verifyUtxoSignedTx',
            request_serializer=savourrpc_dot_wallet__pb2.VerifySignedTxRequest.SerializeToString,
            response_deserializer=savourrpc_dot_wallet__pb2.VerifySignedTxResponse.FromString,
        )


class WalletServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getSupportCoins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def convertAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def validAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getNonce(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getGasPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getMinRent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTx(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getTxByAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getTxByHash(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getUtxo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getUtxoInsFromData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getAccountTxFromData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getUtxoTxFromData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getAccountTxFromSignedData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUtxoTxFromSignedData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createAccountSignedTx(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createAccountTx(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createUtxoSignedTx(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createUtxoTx(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def verifyAccountSignedTx(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def verifyUtxoSignedTx(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WalletServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'getSupportCoins': grpc.unary_unary_rpc_method_handler(
            servicer.getSupportCoins,
            request_deserializer=savourrpc_dot_wallet__pb2.SupportCoinsRequest.FromString,
            response_serializer=savourrpc_dot_wallet__pb2.SupportCoinsResponse.SerializeToString,
        ),
        'convertAddress': grpc.unary_unary_rpc_method_handler(
            servicer.convertAddress,
            request_deserializer=savourrpc_dot_wallet__pb2.ConvertAddressRequest.FromString,
            response_serializer=savourrpc_dot_wallet__pb2.ConvertAddressResponse.SerializeToString,
        ),
        'validAddress': grpc.unary_unary_rpc_method_handler(
            servicer.validAddress,
            request_deserializer=savourrpc_dot_wallet__pb2.ValidAddressRequest.FromString,
            response_serializer=savourrpc_dot_wallet__pb2.ValidAddressResponse.SerializeToString,
        ),
        'getNonce': grpc.unary_unary_rpc_method_handler(
            servicer.getNonce,
            request_deserializer=savourrpc_dot_wallet__pb2.NonceRequest.FromString,
            response_serializer=savourrpc_dot_wallet__pb2.NonceResponse.SerializeToString,
        ),
        'getGasPrice': grpc.unary_unary_rpc_method_handler(
            servicer.getGasPrice,
            request_deserializer=savourrpc_dot_wallet__pb2.GasPriceRequest.FromString,
            response_serializer=savourrpc_dot_wallet__pb2.GasPriceResponse.SerializeToString,
        ),
        'getBalance': grpc.unary_unary_rpc_method_handler(
            servicer.getBalance,
            request_deserializer=savourrpc_dot_wallet__pb2.BalanceRequest.FromString,
            response_serializer=savourrpc_dot_wallet__pb2.BalanceResponse.SerializeToString,
        ),
        'getAccount': grpc.unary_unary_rpc_method_handler(
            servicer.getAccount,
            request_deserializer=savourrpc_dot_wallet__pb2.AccountRequest.FromString,
            response_serializer=savourrpc_dot_wallet__pb2.AccountResponse.SerializeToString,
        ),
        'getMinRent': grpc.unary_unary_rpc_method_handler(
            servicer.getMinRent,
            request_deserializer=savourrpc_dot_wallet__pb2.MinRentRequest.FromString,
            response_serializer=savourrpc_dot_wallet__pb2.MinRentResponse.SerializeToString,
        ),
        'SendTx': grpc.unary_unary_rpc_method_handler(
            servicer.SendTx,
            request_deserializer=savourrpc_dot_wallet__pb2.SendTxRequest.FromString,
            response_serializer=savourrpc_dot_wallet__pb2.SendTxResponse.SerializeToString,
        ),
        'getTxByAddress': grpc.unary_unary_rpc_method_handler(
            servicer.getTxByAddress,
            request_deserializer=savourrpc_dot_wallet__pb2.TxAddressRequest.FromString,
            response_serializer=savourrpc_dot_wallet__pb2.TxAddressResponse.SerializeToString,
        ),
        'getTxByHash': grpc.unary_unary_rpc_method_handler(
            servicer.getTxByHash,
            request_deserializer=savourrpc_dot_wallet__pb2.TxHashRequest.FromString,
            response_serializer=savourrpc_dot_wallet__pb2.TxHashResponse.SerializeToString,
        ),
        'getUtxo': grpc.unary_unary_rpc_method_handler(
            servicer.getUtxo,
            request_deserializer=savourrpc_dot_wallet__pb2.UtxoRequest.FromString,
            response_serializer=savourrpc_dot_wallet__pb2.UtxoResponse.SerializeToString,
        ),
        'getUtxoInsFromData': grpc.unary_unary_rpc_method_handler(
            servicer.getUtxoInsFromData,
            request_deserializer=savourrpc_dot_wallet__pb2.UtxoInsFromDataRequest.FromString,
            response_serializer=savourrpc_dot_wallet__pb2.UtxoInsResponse.SerializeToString,
        ),
        'getAccountTxFromData': grpc.unary_unary_rpc_method_handler(
            servicer.getAccountTxFromData,
            request_deserializer=savourrpc_dot_wallet__pb2.TxFromDataRequest.FromString,
            response_serializer=savourrpc_dot_wallet__pb2.AccountTxResponse.SerializeToString,
        ),
        'getUtxoTxFromData': grpc.unary_unary_rpc_method_handler(
            servicer.getUtxoTxFromData,
            request_deserializer=savourrpc_dot_wallet__pb2.TxFromDataRequest.FromString,
            response_serializer=savourrpc_dot_wallet__pb2.UtxoTxResponse.SerializeToString,
        ),
        'getAccountTxFromSignedData': grpc.unary_unary_rpc_method_handler(
            servicer.getAccountTxFromSignedData,
            request_deserializer=savourrpc_dot_wallet__pb2.TxFromSignedDataRequest.FromString,
            response_serializer=savourrpc_dot_wallet__pb2.AccountTxResponse.SerializeToString,
        ),
        'GetUtxoTxFromSignedData': grpc.unary_unary_rpc_method_handler(
            servicer.GetUtxoTxFromSignedData,
            request_deserializer=savourrpc_dot_wallet__pb2.TxFromSignedDataRequest.FromString,
            response_serializer=savourrpc_dot_wallet__pb2.UtxoTxResponse.SerializeToString,
        ),
        'createAccountSignedTx': grpc.unary_unary_rpc_method_handler(
            servicer.createAccountSignedTx,
            request_deserializer=savourrpc_dot_wallet__pb2.CreateAccountSignedTxRequest.FromString,
            response_serializer=savourrpc_dot_wallet__pb2.CreateSignedTxResponse.SerializeToString,
        ),
        'createAccountTx': grpc.unary_unary_rpc_method_handler(
            servicer.createAccountTx,
            request_deserializer=savourrpc_dot_wallet__pb2.CreateAccountTxRequest.FromString,
            response_serializer=savourrpc_dot_wallet__pb2.CreateAccountTxResponse.SerializeToString,
        ),
        'createUtxoSignedTx': grpc.unary_unary_rpc_method_handler(
            servicer.createUtxoSignedTx,
            request_deserializer=savourrpc_dot_wallet__pb2.CreateUtxoSignedTxRequest.FromString,
            response_serializer=savourrpc_dot_wallet__pb2.CreateSignedTxResponse.SerializeToString,
        ),
        'createUtxoTx': grpc.unary_unary_rpc_method_handler(
            servicer.createUtxoTx,
            request_deserializer=savourrpc_dot_wallet__pb2.CreateUtxoTxRequest.FromString,
            response_serializer=savourrpc_dot_wallet__pb2.CreateUtxoTxResponse.SerializeToString,
        ),
        'verifyAccountSignedTx': grpc.unary_unary_rpc_method_handler(
            servicer.verifyAccountSignedTx,
            request_deserializer=savourrpc_dot_wallet__pb2.VerifySignedTxRequest.FromString,
            response_serializer=savourrpc_dot_wallet__pb2.VerifySignedTxResponse.SerializeToString,
        ),
        'verifyUtxoSignedTx': grpc.unary_unary_rpc_method_handler(
            servicer.verifyUtxoSignedTx,
            request_deserializer=savourrpc_dot_wallet__pb2.VerifySignedTxRequest.FromString,
            response_serializer=savourrpc_dot_wallet__pb2.VerifySignedTxResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'savourrpc.wallet.WalletService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class WalletService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getSupportCoins(request,
                        target,
                        options=(),
                        channel_credentials=None,
                        call_credentials=None,
                        insecure=False,
                        compression=None,
                        wait_for_ready=None,
                        timeout=None,
                        metadata=None):
        return grpc.experimental.unary_unary(request, target, '/savourrpc.wallet.WalletService/getSupportCoins',
                                             savourrpc_dot_wallet__pb2.SupportCoinsRequest.SerializeToString,
                                             savourrpc_dot_wallet__pb2.SupportCoinsResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def convertAddress(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
        return grpc.experimental.unary_unary(request, target, '/savourrpc.wallet.WalletService/convertAddress',
                                             savourrpc_dot_wallet__pb2.ConvertAddressRequest.SerializeToString,
                                             savourrpc_dot_wallet__pb2.ConvertAddressResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def validAddress(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
        return grpc.experimental.unary_unary(request, target, '/savourrpc.wallet.WalletService/validAddress',
                                             savourrpc_dot_wallet__pb2.ValidAddressRequest.SerializeToString,
                                             savourrpc_dot_wallet__pb2.ValidAddressResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getNonce(request,
                 target,
                 options=(),
                 channel_credentials=None,
                 call_credentials=None,
                 insecure=False,
                 compression=None,
                 wait_for_ready=None,
                 timeout=None,
                 metadata=None):
        return grpc.experimental.unary_unary(request, target, '/savourrpc.wallet.WalletService/getNonce',
                                             savourrpc_dot_wallet__pb2.NonceRequest.SerializeToString,
                                             savourrpc_dot_wallet__pb2.NonceResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getGasPrice(request,
                    target,
                    options=(),
                    channel_credentials=None,
                    call_credentials=None,
                    insecure=False,
                    compression=None,
                    wait_for_ready=None,
                    timeout=None,
                    metadata=None):
        return grpc.experimental.unary_unary(request, target, '/savourrpc.wallet.WalletService/getGasPrice',
                                             savourrpc_dot_wallet__pb2.GasPriceRequest.SerializeToString,
                                             savourrpc_dot_wallet__pb2.GasPriceResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getBalance(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
        return grpc.experimental.unary_unary(request, target, '/savourrpc.wallet.WalletService/getBalance',
                                             savourrpc_dot_wallet__pb2.BalanceRequest.SerializeToString,
                                             savourrpc_dot_wallet__pb2.BalanceResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getAccount(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
        return grpc.experimental.unary_unary(request, target, '/savourrpc.wallet.WalletService/getAccount',
                                             savourrpc_dot_wallet__pb2.AccountRequest.SerializeToString,
                                             savourrpc_dot_wallet__pb2.AccountResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getMinRent(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
        return grpc.experimental.unary_unary(request, target, '/savourrpc.wallet.WalletService/getMinRent',
                                             savourrpc_dot_wallet__pb2.MinRentRequest.SerializeToString,
                                             savourrpc_dot_wallet__pb2.MinRentResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendTx(request,
               target,
               options=(),
               channel_credentials=None,
               call_credentials=None,
               insecure=False,
               compression=None,
               wait_for_ready=None,
               timeout=None,
               metadata=None):
        return grpc.experimental.unary_unary(request, target, '/savourrpc.wallet.WalletService/SendTx',
                                             savourrpc_dot_wallet__pb2.SendTxRequest.SerializeToString,
                                             savourrpc_dot_wallet__pb2.SendTxResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getTxByAddress(request,
                       target,
                       options=(),
                       channel_credentials=None,
                       call_credentials=None,
                       insecure=False,
                       compression=None,
                       wait_for_ready=None,
                       timeout=None,
                       metadata=None):
        return grpc.experimental.unary_unary(request, target, '/savourrpc.wallet.WalletService/getTxByAddress',
                                             savourrpc_dot_wallet__pb2.TxAddressRequest.SerializeToString,
                                             savourrpc_dot_wallet__pb2.TxAddressResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getTxByHash(request,
                    target,
                    options=(),
                    channel_credentials=None,
                    call_credentials=None,
                    insecure=False,
                    compression=None,
                    wait_for_ready=None,
                    timeout=None,
                    metadata=None):
        return grpc.experimental.unary_unary(request, target, '/savourrpc.wallet.WalletService/getTxByHash',
                                             savourrpc_dot_wallet__pb2.TxHashRequest.SerializeToString,
                                             savourrpc_dot_wallet__pb2.TxHashResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getUtxo(request,
                target,
                options=(),
                channel_credentials=None,
                call_credentials=None,
                insecure=False,
                compression=None,
                wait_for_ready=None,
                timeout=None,
                metadata=None):
        return grpc.experimental.unary_unary(request, target, '/savourrpc.wallet.WalletService/getUtxo',
                                             savourrpc_dot_wallet__pb2.UtxoRequest.SerializeToString,
                                             savourrpc_dot_wallet__pb2.UtxoResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getUtxoInsFromData(request,
                           target,
                           options=(),
                           channel_credentials=None,
                           call_credentials=None,
                           insecure=False,
                           compression=None,
                           wait_for_ready=None,
                           timeout=None,
                           metadata=None):
        return grpc.experimental.unary_unary(request, target, '/savourrpc.wallet.WalletService/getUtxoInsFromData',
                                             savourrpc_dot_wallet__pb2.UtxoInsFromDataRequest.SerializeToString,
                                             savourrpc_dot_wallet__pb2.UtxoInsResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getAccountTxFromData(request,
                             target,
                             options=(),
                             channel_credentials=None,
                             call_credentials=None,
                             insecure=False,
                             compression=None,
                             wait_for_ready=None,
                             timeout=None,
                             metadata=None):
        return grpc.experimental.unary_unary(request, target, '/savourrpc.wallet.WalletService/getAccountTxFromData',
                                             savourrpc_dot_wallet__pb2.TxFromDataRequest.SerializeToString,
                                             savourrpc_dot_wallet__pb2.AccountTxResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getUtxoTxFromData(request,
                          target,
                          options=(),
                          channel_credentials=None,
                          call_credentials=None,
                          insecure=False,
                          compression=None,
                          wait_for_ready=None,
                          timeout=None,
                          metadata=None):
        return grpc.experimental.unary_unary(request, target, '/savourrpc.wallet.WalletService/getUtxoTxFromData',
                                             savourrpc_dot_wallet__pb2.TxFromDataRequest.SerializeToString,
                                             savourrpc_dot_wallet__pb2.UtxoTxResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getAccountTxFromSignedData(request,
                                   target,
                                   options=(),
                                   channel_credentials=None,
                                   call_credentials=None,
                                   insecure=False,
                                   compression=None,
                                   wait_for_ready=None,
                                   timeout=None,
                                   metadata=None):
        return grpc.experimental.unary_unary(request, target,
                                             '/savourrpc.wallet.WalletService/getAccountTxFromSignedData',
                                             savourrpc_dot_wallet__pb2.TxFromSignedDataRequest.SerializeToString,
                                             savourrpc_dot_wallet__pb2.AccountTxResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUtxoTxFromSignedData(request,
                                target,
                                options=(),
                                channel_credentials=None,
                                call_credentials=None,
                                insecure=False,
                                compression=None,
                                wait_for_ready=None,
                                timeout=None,
                                metadata=None):
        return grpc.experimental.unary_unary(request, target, '/savourrpc.wallet.WalletService/GetUtxoTxFromSignedData',
                                             savourrpc_dot_wallet__pb2.TxFromSignedDataRequest.SerializeToString,
                                             savourrpc_dot_wallet__pb2.UtxoTxResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createAccountSignedTx(request,
                              target,
                              options=(),
                              channel_credentials=None,
                              call_credentials=None,
                              insecure=False,
                              compression=None,
                              wait_for_ready=None,
                              timeout=None,
                              metadata=None):
        return grpc.experimental.unary_unary(request, target, '/savourrpc.wallet.WalletService/createAccountSignedTx',
                                             savourrpc_dot_wallet__pb2.CreateAccountSignedTxRequest.SerializeToString,
                                             savourrpc_dot_wallet__pb2.CreateSignedTxResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createAccountTx(request,
                        target,
                        options=(),
                        channel_credentials=None,
                        call_credentials=None,
                        insecure=False,
                        compression=None,
                        wait_for_ready=None,
                        timeout=None,
                        metadata=None):
        return grpc.experimental.unary_unary(request, target, '/savourrpc.wallet.WalletService/createAccountTx',
                                             savourrpc_dot_wallet__pb2.CreateAccountTxRequest.SerializeToString,
                                             savourrpc_dot_wallet__pb2.CreateAccountTxResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createUtxoSignedTx(request,
                           target,
                           options=(),
                           channel_credentials=None,
                           call_credentials=None,
                           insecure=False,
                           compression=None,
                           wait_for_ready=None,
                           timeout=None,
                           metadata=None):
        return grpc.experimental.unary_unary(request, target, '/savourrpc.wallet.WalletService/createUtxoSignedTx',
                                             savourrpc_dot_wallet__pb2.CreateUtxoSignedTxRequest.SerializeToString,
                                             savourrpc_dot_wallet__pb2.CreateSignedTxResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def createUtxoTx(request,
                     target,
                     options=(),
                     channel_credentials=None,
                     call_credentials=None,
                     insecure=False,
                     compression=None,
                     wait_for_ready=None,
                     timeout=None,
                     metadata=None):
        return grpc.experimental.unary_unary(request, target, '/savourrpc.wallet.WalletService/createUtxoTx',
                                             savourrpc_dot_wallet__pb2.CreateUtxoTxRequest.SerializeToString,
                                             savourrpc_dot_wallet__pb2.CreateUtxoTxResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def verifyAccountSignedTx(request,
                              target,
                              options=(),
                              channel_credentials=None,
                              call_credentials=None,
                              insecure=False,
                              compression=None,
                              wait_for_ready=None,
                              timeout=None,
                              metadata=None):
        return grpc.experimental.unary_unary(request, target, '/savourrpc.wallet.WalletService/verifyAccountSignedTx',
                                             savourrpc_dot_wallet__pb2.VerifySignedTxRequest.SerializeToString,
                                             savourrpc_dot_wallet__pb2.VerifySignedTxResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def verifyUtxoSignedTx(request,
                           target,
                           options=(),
                           channel_credentials=None,
                           call_credentials=None,
                           insecure=False,
                           compression=None,
                           wait_for_ready=None,
                           timeout=None,
                           metadata=None):
        return grpc.experimental.unary_unary(request, target, '/savourrpc.wallet.WalletService/verifyUtxoSignedTx',
                                             savourrpc_dot_wallet__pb2.VerifySignedTxRequest.SerializeToString,
                                             savourrpc_dot_wallet__pb2.VerifySignedTxResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
