# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coincorerpc/common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x63oincorerpc/common.proto\x12\x0b\x63oincorerpc\"G\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\r\n\x05\x62rief\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x65tail\x18\x03 \x01(\t\x12\x11\n\tcan_retry\x18\x04 \x01(\x08\"\x07\n\x05\x45mptyB=Z;git.coincore.com/coincore/coincorerpc/go-coincorerpc/commonb\x06proto3')



_ERROR = DESCRIPTOR.message_types_by_name['Error']
_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
Error = _reflection.GeneratedProtocolMessageType('Error', (_message.Message,), {
  'DESCRIPTOR' : _ERROR,
  '__module__' : 'coincorerpc.common_pb2'
  # @@protoc_insertion_point(class_scope:coincorerpc.Error)
  })
_sym_db.RegisterMessage(Error)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'coincorerpc.common_pb2'
  # @@protoc_insertion_point(class_scope:coincorerpc.Empty)
  })
_sym_db.RegisterMessage(Empty)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z;git.coincore.com/coincore/coincorerpc/go-coincorerpc/common'
  _ERROR._serialized_start=41
  _ERROR._serialized_end=112
  _EMPTY._serialized_start=114
  _EMPTY._serialized_end=121
# @@protoc_insertion_point(module_scope)
