# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from sevices.coincorerpc import market_pb2 as coincorerpc_dot_market__pb2


class MarketPriceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getMarket = channel.unary_unary(
                '/coincorerpc.market.MarketPriceService/getMarket',
                request_serializer=coincorerpc_dot_market__pb2.MarketPriceRequest.SerializeToString,
                response_deserializer=coincorerpc_dot_market__pb2.MarketPriceResponse.FromString,
                )


class MarketPriceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getMarket(self, request, context):
        """主站向行情服务请求数据
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketPriceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getMarket': grpc.unary_unary_rpc_method_handler(
                    servicer.getMarket,
                    request_deserializer=coincorerpc_dot_market__pb2.MarketPriceRequest.FromString,
                    response_serializer=coincorerpc_dot_market__pb2.MarketPriceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coincorerpc.market.MarketPriceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MarketPriceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getMarket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/coincorerpc.market.MarketPriceService/getMarket',
            coincorerpc_dot_market__pb2.MarketPriceRequest.SerializeToString,
            coincorerpc_dot_market__pb2.MarketPriceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
